# [**Numpy - Numerical Python**](https://numpy.org/doc/stable/)
* One of most powerful popular third party library
* For **scientific computation**
* **`ndarray`**-N-dimensional Array most important component
* faster than python arrays (because C code compilation is associated with numpy which is faster than python code)

Application
* Scientific Domain
* Data Science
* Machine Learning 
* Visualization


Package Installation cmd using pip

**`pip install numpy`**


In [1]:
try:
    import numpy as np
except ImportError:
    import os
    os.system("pip install numpy")
    
    import numpy as np

`asarray()` list to numpy array 


In [2]:
application = [32000, 16000, 8000, 4000]
np_application = np.asarray(application)
np_application

array([32000, 16000,  8000,  4000])

In [3]:
type(np_application)

numpy.ndarray

`.shape` attribute

In [4]:
np_application.shape

(4,)

`.dtype` attribute

In [5]:
np_application.dtype

dtype('int32')

`.zeros()` functions

In [6]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np.ones((3,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [10]:
np.arange((10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(start=2,stop=20,step=2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0,10,2)

array([ 0., 10.])

In [13]:
np.linspace(start=2,stop=20,num=10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [14]:
np.random.random((2,2))

array([[0.18885487, 0.82923627],
       [0.04490575, 0.25495681]])